auto_scale_lr = dict(base_batch_size=64, enable=False)
backend_args = None
data_root = '/home/zero/USER/HEYU/mmdetection3d/data/scannet/'
dataset_type = 'ScanNetDataset'
default_hooks = dict(
    checkpoint=dict(interval=-1, type='CheckpointHook'),
    logger=dict(interval=30, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='Det3DVisualizationHook'))
default_scope = 'mmdet3d'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
launcher = 'none'
load_from = None
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
lr = 0.008
metainfo = dict(
    classes=(
        'cabinet',
        'bed',
        'chair',
        'sofa',
        'table',
        'door',
        'window',
        'bookshelf',
        'picture',
        'counter',
        'desk',
        'curtain',
        'refrigerator',
        'showercurtrain',
        'toilet',
        'sink',
        'bathtub',
        'garbagebin',
    ))
model = dict(
    backbone=dict(
        fp_channels=(
            (
                256,
                256,
            ),
            (
                256,
                256,
            ),
        ),
        in_channels=4,
        norm_cfg=dict(type='BN2d'),
        num_points=(
            2048,
            1024,
            512,
            256,
        ),
        num_samples=(
            64,
            32,
            16,
            16,
        ),
        radius=(
            0.2,
            0.4,
            0.8,
            1.2,
        ),
        sa_cfg=dict(
            normalize_xyz=True,
            pool_mod='max',
            type='PointSAModule',
            use_xyz=True),
        sa_channels=(
            (
                64,
                64,
                128,
            ),
            (
                128,
                128,
                256,
            ),
            (
                128,
                128,
                256,
            ),
            (
                128,
                128,
                256,
            ),
        ),
        type='PointNet2SASSG'),
    bbox_head=dict(
        bbox_coder=dict(
            mean_sizes=[
                [
                    0.76966727,
                    0.8116021,
                    0.92573744,
                ],
                [
                    1.876858,
                    1.8425595,
                    1.1931566,
                ],
                [
                    0.61328,
                    0.6148609,
                    0.7182701,
                ],
                [
                    1.3955007,
                    1.5121545,
                    0.83443564,
                ],
                [
                    0.97949594,
                    1.0675149,
                    0.6329687,
                ],
                [
                    0.531663,
                    0.5955577,
                    1.7500148,
                ],
                [
                    0.9624706,
                    0.72462326,
                    1.1481868,
                ],
                [
                    0.83221924,
                    1.0490936,
                    1.6875663,
                ],
                [
                    0.21132214,
                    0.4206159,
                    0.5372846,
                ],
                [
                    1.4440073,
                    1.8970833,
                    0.26985747,
                ],
                [
                    1.0294262,
                    1.4040797,
                    0.87554324,
                ],
                [
                    1.3766412,
                    0.65521795,
                    1.6813129,
                ],
                [
                    0.6650819,
                    0.71111923,
                    1.298853,
                ],
                [
                    0.41999173,
                    0.37906948,
                    1.7513971,
                ],
                [
                    0.59359556,
                    0.5912492,
                    0.73919016,
                ],
                [
                    0.50867593,
                    0.50656086,
                    0.30136237,
                ],
                [
                    1.1511526,
                    1.0546296,
                    0.49706793,
                ],
                [
                    0.47535285,
                    0.49249494,
                    0.5802117,
                ],
            ],
            num_dir_bins=1,
            num_sizes=18,
            type='PartialBinBasedBBoxCoder',
            with_rot=False),
        center_loss=dict(
            loss_dst_weight=10.0,
            loss_src_weight=10.0,
            mode='l2',
            reduction='sum',
            type='ChamferDistance'),
        dir_class_loss=dict(
            loss_weight=1.0, reduction='sum', type='mmdet.CrossEntropyLoss'),
        dir_res_loss=dict(
            loss_weight=10.0, reduction='sum', type='mmdet.SmoothL1Loss'),
        num_classes=18,
        objectness_loss=dict(
            class_weight=[
                0.2,
                0.8,
            ],
            loss_weight=5.0,
            reduction='sum',
            type='mmdet.CrossEntropyLoss'),
        pred_layer_cfg=dict(
            bias=True, in_channels=128, shared_conv_channels=(
                128,
                128,
            )),
        semantic_loss=dict(
            loss_weight=1.0, reduction='sum', type='mmdet.CrossEntropyLoss'),
        size_class_loss=dict(
            loss_weight=1.0, reduction='sum', type='mmdet.CrossEntropyLoss'),
        size_res_loss=dict(
            loss_weight=3.3333333333333335,
            reduction='sum',
            type='mmdet.SmoothL1Loss'),
        type='VoteHead',
        vote_aggregation_cfg=dict(
            mlp_channels=[
                256,
                128,
                128,
                128,
            ],
            normalize_xyz=True,
            num_point=256,
            num_sample=16,
            radius=0.3,
            type='PointSAModule',
            use_xyz=True),
        vote_module_cfg=dict(
            conv_cfg=dict(type='Conv1d'),
            conv_channels=(
                256,
                256,
            ),
            gt_per_seed=3,
            in_channels=256,
            norm_cfg=dict(type='BN1d'),
            norm_feats=True,
            vote_loss=dict(
                loss_dst_weight=10.0,
                mode='l1',
                reduction='none',
                type='ChamferDistance'),
            vote_per_seed=1)),
    data_preprocessor=dict(type='Det3DDataPreprocessor'),
    test_cfg=dict(
        nms_thr=0.25,
        per_class_proposal=True,
        sample_mode='seed',
        score_thr=0.05),
    train_cfg=dict(
        neg_distance_thr=0.6, pos_distance_thr=0.3, sample_mode='vote'),
    type='VoteNet')
optim_wrapper = dict(
    clip_grad=dict(max_norm=10, norm_type=2),
    optimizer=dict(lr=0.008, type='AdamW', weight_decay=0.01),
    type='OptimWrapper')
param_scheduler = [
    dict(
        begin=0,
        by_epoch=True,
        end=36,
        gamma=0.1,
        milestones=[
            24,
            32,
        ],
        type='MultiStepLR'),
]
resume = False
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='scannet_infos_val.pkl',
        backend_args=None,
        box_type_3d='Depth',
        data_root='/home/zero/USER/HEYU/mmdetection3d/data/scannet/',
        metainfo=dict(
            classes=(
                'cabinet',
                'bed',
                'chair',
                'sofa',
                'table',
                'door',
                'window',
                'bookshelf',
                'picture',
                'counter',
                'desk',
                'curtain',
                'refrigerator',
                'showercurtrain',
                'toilet',
                'sink',
                'bathtub',
                'garbagebin',
            )),
        pipeline=[
            dict(
                backend_args=None,
                coord_type='DEPTH',
                load_dim=6,
                shift_height=True,
                type='LoadPointsFromFile',
                use_dim=[
                    0,
                    1,
                    2,
                ]),
            dict(rotation_axis=2, type='GlobalAlignment'),
            dict(
                flip=False,
                img_scale=(
                    1333,
                    800,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        rot_range=[
                            0,
                            0,
                        ],
                        scale_ratio_range=[
                            1.0,
                            1.0,
                        ],
                        translation_std=[
                            0,
                            0,
                            0,
                        ],
                        type='GlobalRotScaleTrans'),
                    dict(
                        flip_ratio_bev_horizontal=0.5,
                        flip_ratio_bev_vertical=0.5,
                        sync_2d=False,
                        type='RandomFlip3D'),
                    dict(num_points=40000, type='PointSample'),
                ],
                type='MultiScaleFlipAug3D'),
            dict(keys=[
                'points',
            ], type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='ScanNetDataset'),
    num_workers=1,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(type='IndoorMetric')
test_pipeline = [
    dict(
        backend_args=None,
        coord_type='DEPTH',
        load_dim=6,
        shift_height=True,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
        ]),
    dict(rotation_axis=2, type='GlobalAlignment'),
    dict(
        flip=False,
        img_scale=(
            1333,
            800,
        ),
        pts_scale_ratio=1,
        transforms=[
            dict(
                rot_range=[
                    0,
                    0,
                ],
                scale_ratio_range=[
                    1.0,
                    1.0,
                ],
                translation_std=[
                    0,
                    0,
                    0,
                ],
                type='GlobalRotScaleTrans'),
            dict(
                flip_ratio_bev_horizontal=0.5,
                flip_ratio_bev_vertical=0.5,
                sync_2d=False,
                type='RandomFlip3D'),
            dict(num_points=40000, type='PointSample'),
        ],
        type='MultiScaleFlipAug3D'),
    dict(keys=[
        'points',
    ], type='Pack3DDetInputs'),
]
train_cfg = dict(max_epochs=36, type='EpochBasedTrainLoop', val_interval=36)
train_dataloader = dict(
    batch_size=8,
    dataset=dict(
        dataset=dict(
            ann_file='scannet_infos_train.pkl',
            backend_args=None,
            box_type_3d='Depth',
            data_root='/home/zero/USER/HEYU/mmdetection3d/data/scannet/',
            filter_empty_gt=False,
            metainfo=dict(
                classes=(
                    'cabinet',
                    'bed',
                    'chair',
                    'sofa',
                    'table',
                    'door',
                    'window',
                    'bookshelf',
                    'picture',
                    'counter',
                    'desk',
                    'curtain',
                    'refrigerator',
                    'showercurtrain',
                    'toilet',
                    'sink',
                    'bathtub',
                    'garbagebin',
                )),
            pipeline=[
                dict(
                    backend_args=None,
                    coord_type='DEPTH',
                    load_dim=6,
                    shift_height=True,
                    type='LoadPointsFromFile',
                    use_dim=[
                        0,
                        1,
                        2,
                    ]),
                dict(
                    backend_args=None,
                    type='LoadAnnotations3D',
                    with_bbox_3d=True,
                    with_label_3d=True,
                    with_mask_3d=True,
                    with_seg_3d=True),
                dict(rotation_axis=2, type='GlobalAlignment'),
                dict(type='PointSegClassMapping'),
                dict(num_points=40000, type='PointSample'),
                dict(
                    flip_ratio_bev_horizontal=0.5,
                    flip_ratio_bev_vertical=0.5,
                    sync_2d=False,
                    type='RandomFlip3D'),
                dict(
                    rot_range=[
                        -0.087266,
                        0.087266,
                    ],
                    scale_ratio_range=[
                        1.0,
                        1.0,
                    ],
                    shift_height=True,
                    type='GlobalRotScaleTrans'),
                dict(
                    keys=[
                        'points',
                        'gt_bboxes_3d',
                        'gt_labels_3d',
                        'pts_semantic_mask',
                        'pts_instance_mask',
                    ],
                    type='Pack3DDetInputs'),
            ],
            type='ScanNetDataset'),
        times=5,
        type='RepeatDataset'),
    num_workers=4,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        backend_args=None,
        coord_type='DEPTH',
        load_dim=6,
        shift_height=True,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
        ]),
    dict(
        backend_args=None,
        type='LoadAnnotations3D',
        with_bbox_3d=True,
        with_label_3d=True,
        with_mask_3d=True,
        with_seg_3d=True),
    dict(rotation_axis=2, type='GlobalAlignment'),
    dict(type='PointSegClassMapping'),
    dict(num_points=40000, type='PointSample'),
    dict(
        flip_ratio_bev_horizontal=0.5,
        flip_ratio_bev_vertical=0.5,
        sync_2d=False,
        type='RandomFlip3D'),
    dict(
        rot_range=[
            -0.087266,
            0.087266,
        ],
        scale_ratio_range=[
            1.0,
            1.0,
        ],
        shift_height=True,
        type='GlobalRotScaleTrans'),
    dict(
        keys=[
            'points',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'pts_semantic_mask',
            'pts_instance_mask',
        ],
        type='Pack3DDetInputs'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='scannet_infos_val.pkl',
        backend_args=None,
        box_type_3d='Depth',
        data_root='/home/zero/USER/HEYU/mmdetection3d/data/scannet/',
        metainfo=dict(
            classes=(
                'cabinet',
                'bed',
                'chair',
                'sofa',
                'table',
                'door',
                'window',
                'bookshelf',
                'picture',
                'counter',
                'desk',
                'curtain',
                'refrigerator',
                'showercurtrain',
                'toilet',
                'sink',
                'bathtub',
                'garbagebin',
            )),
        pipeline=[
            dict(
                backend_args=None,
                coord_type='DEPTH',
                load_dim=6,
                shift_height=True,
                type='LoadPointsFromFile',
                use_dim=[
                    0,
                    1,
                    2,
                ]),
            dict(rotation_axis=2, type='GlobalAlignment'),
            dict(
                flip=False,
                img_scale=(
                    1333,
                    800,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        rot_range=[
                            0,
                            0,
                        ],
                        scale_ratio_range=[
                            1.0,
                            1.0,
                        ],
                        translation_std=[
                            0,
                            0,
                            0,
                        ],
                        type='GlobalRotScaleTrans'),
                    dict(
                        flip_ratio_bev_horizontal=0.5,
                        flip_ratio_bev_vertical=0.5,
                        sync_2d=False,
                        type='RandomFlip3D'),
                    dict(num_points=40000, type='PointSample'),
                ],
                type='MultiScaleFlipAug3D'),
            dict(keys=[
                'points',
            ], type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='ScanNetDataset'),
    num_workers=1,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(type='IndoorMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='Det3DLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = '/home/zero/USER/HEYU/mmdetection3d/work_dirs/scannet/DFF_VoteNet/4'
